# Generated by Django 4.1.7 on 2023-07-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DigimonAtribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attr_id", models.IntegerField(verbose_name="id")),
                (
                    "attr_name",
                    models.CharField(max_length=50, verbose_name="attribute"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigimonDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=50, verbose_name="origin")),
                ("language", models.CharField(max_length=20, verbose_name="language")),
                ("description", models.TextField(verbose_name="description")),
            ],
        ),
        migrations.CreateModel(
            name="DigimonEvolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evo_id", models.IntegerField(verbose_name="id")),
                ("evo_name", models.CharField(max_length=100, verbose_name="digimon")),
                (
                    "evo_condition",
                    models.CharField(max_length=100, verbose_name="condition"),
                ),
                ("evo_image", models.URLField(verbose_name="image")),
                ("evo_link", models.URLField(verbose_name="url")),
            ],
        ),
        migrations.CreateModel(
            name="DigimonField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_id", models.IntegerField(verbose_name="id")),
                ("field_name", models.CharField(max_length=50, verbose_name="field")),
                ("image", models.URLField(verbose_name="image")),
            ],
        ),
        migrations.CreateModel(
            name="DigimonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("href", models.URLField(verbose_name="href")),
                ("transparent", models.BooleanField(verbose_name="Transparent")),
            ],
        ),
        migrations.CreateModel(
            name="DigimonLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_id", models.IntegerField(verbose_name="id")),
                ("level_name", models.CharField(max_length=50, verbose_name="level")),
            ],
        ),
        migrations.CreateModel(
            name="DigimonSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.IntegerField(verbose_name="id")),
                ("skill_name", models.CharField(max_length=100, verbose_name="skill")),
                (
                    "translation",
                    models.CharField(max_length=100, verbose_name="translation"),
                ),
                ("description", models.TextField(verbose_name="description")),
            ],
        ),
        migrations.CreateModel(
            name="Digimon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("antibody", models.BooleanField(verbose_name="xAntibody")),
                (
                    "release_date",
                    models.CharField(max_length=4, verbose_name="releaseDate"),
                ),
                ("comments", models.TextField(verbose_name="Comments")),
                (
                    "attributes",
                    models.ManyToManyField(
                        related_name="attributes", to="main.digimonatribute"
                    ),
                ),
                (
                    "descriptions",
                    models.ManyToManyField(
                        related_name="descriptions", to="main.digimondescription"
                    ),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        related_name="fields", to="main.digimonfield"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="images", to="main.digimonimage"
                    ),
                ),
                (
                    "levels",
                    models.ManyToManyField(
                        related_name="levels", to="main.digimonlevel"
                    ),
                ),
                (
                    "next_evos",
                    models.ManyToManyField(
                        related_name="nextEvolutions", to="main.digimonevolution"
                    ),
                ),
                (
                    "prior_evos",
                    models.ManyToManyField(
                        related_name="priorEvolutions", to="main.digimonevolution"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="skills", to="main.digimonskill"
                    ),
                ),
            ],
        ),
    ]
