# Generated by Django 4.1.7 on 2023-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digimon",
            name="profile",
            field=models.ManyToManyField(
                related_name="profile", to="account.userprofilemodel"
            ),
        ),
    ]
