# Generated by Django 4.1.7 on 2023-07-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_digimon_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="digimon", name="profile",),
    ]
