# Generated by Django 4.1.7 on 2023-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_digimon_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digimon",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="digimonatribute",
            name="attr_name",
            field=models.CharField(max_length=100, verbose_name="attribute"),
        ),
        migrations.AlterField(
            model_name="digimonevolution",
            name="evo_condition",
            field=models.CharField(max_length=200, verbose_name="condition"),
        ),
        migrations.AlterField(
            model_name="digimonevolution",
            name="evo_name",
            field=models.CharField(max_length=200, verbose_name="digimon"),
        ),
        migrations.AlterField(
            model_name="digimonfield",
            name="field_name",
            field=models.CharField(max_length=100, verbose_name="field"),
        ),
        migrations.AlterField(
            model_name="digimonlevel",
            name="level_name",
            field=models.CharField(max_length=100, verbose_name="level"),
        ),
        migrations.AlterField(
            model_name="digimonskill",
            name="skill_name",
            field=models.CharField(max_length=200, verbose_name="skill"),
        ),
        migrations.AlterField(
            model_name="digimonskill",
            name="translation",
            field=models.CharField(max_length=200, verbose_name="translation"),
        ),
    ]
