# Generated by Django 4.1.7 on 2023-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_digimon_name_alter_digimonatribute_attr_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digimon",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="digimonevolution",
            name="evo_condition",
            field=models.CharField(max_length=500, verbose_name="condition"),
        ),
        migrations.AlterField(
            model_name="digimonevolution",
            name="evo_name",
            field=models.CharField(max_length=500, verbose_name="digimon"),
        ),
        migrations.AlterField(
            model_name="digimonskill",
            name="skill_name",
            field=models.CharField(max_length=500, verbose_name="skill"),
        ),
        migrations.AlterField(
            model_name="digimonskill",
            name="translation",
            field=models.CharField(max_length=500, verbose_name="translation"),
        ),
    ]
