# Generated by Django 4.1.7 on 2023-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest User",
                "verbose_name_plural": "Guest Users",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=64, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
                (
                    "first_name",
                    models.CharField(max_length=64, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=64, verbose_name="Last Name"),
                ),
            ],
            options={
                "verbose_name": "Registered User",
                "verbose_name_plural": "Registered Users",
            },
        ),
    ]
