# Generated by Django 4.1.7 on 2023-07-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmarks",
            field=models.ManyToManyField(related_name="bookmarks", to="main.digimon"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="digimons",
            field=models.ManyToManyField(related_name="digimons", to="main.digimon"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=6,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
