# Generated by Django 4.1.7 on 2023-08-05 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="first_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z]+$", "Must contain only letters!"
                    ),
                    django.core.validators.RegexValidator(
                        "^.{2,}$", "Must contain at least 2 symbols!"
                    ),
                ],
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z]+$", "Must contain only letters!"
                    ),
                    django.core.validators.RegexValidator(
                        "^.{2,}$", "Must contain at least 2 symbols!"
                    ),
                ],
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="password",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^.{8,}$", "Must contain at least 8 symbols!"
                    )
                ],
                verbose_name="Password",
            ),
        ),
    ]
