# Generated by Django 4.1.7 on 2023-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userprofile_age_alter_userprofile_bookmarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.URLField(
                blank=True, null=True, verbose_name="Profile Picture"
            ),
        ),
    ]
